-- @leb-regression-guard:lightning-blast-chain-rehit
-- See REGRESSION_GUARDS.md "lightning-blast-chain-rehit",
-- Validation provenance is retained in maintainer notes.

local function readFile(path)
    local f = io.open(path, "r") or io.open("src/" .. path, "r")
    if not f then return nil end
    local s = f:read("*a"); f:close()
    return s
end

local function single(mods)
    assert.are.equals(1, #mods)
    return mods[1]
end

describe("Lightning Blast Convergence flags parse (were ModCache NO-OPs)", function()
    it("' Lightning Blast Chains Only To First Target Hit' -> ChainsBackOnItself FLAG", function()
        local mods, extra = modLib.parseMod(" Lightning Blast Chains Only To First Target Hit")
        assert.is_truthy(extra == nil or extra == "")
        local m = single(mods)
        assert.are.equals("LightningBlastChainsBackOnItself", m.name)
        assert.are.equals("FLAG", m.type)
        assert.is_true(m.value)
    end)
    it("' Half Maximum Chains' -> HalfChains FLAG", function()
        local mods, extra = modLib.parseMod(" Half Maximum Chains")
        assert.is_truthy(extra == nil or extra == "")
        local m = single(mods)
        assert.are.equals("LightningBlastHalfChains", m.name)
        assert.are.equals("FLAG", m.type)
        assert.is_true(m.value)
    end)
end)

describe("Lightning Blast chain-count parsing (per-point + point-scaled)", function()
    -- Arcing Power (no '+'): 1-point cache row + >1-point scaled live-parse.
    it("'1 Maximum Additional Chains' -> MaxAdditionalChains BASE 1", function()
        local mods, extra = modLib.parseMod("1 Maximum Additional Chains")
        assert.is_truthy(extra == nil or extra == "",
            "was dropped with ' Maximum Additional Chains ' residue")
        local m = single(mods)
        assert.are.equals("MaxAdditionalChains", m.name)
        assert.are.equals("BASE", m.type)
        assert.are.equals(1, m.value)
    end)
    it("point-scaled '3 Maximum Additional Chains' (Arcing 3pt) -> BASE 3", function()
        local m = single(modLib.parseMod("3 Maximum Additional Chains"))
        assert.are.equals("MaxAdditionalChains", m.name)
        assert.are.equals(3, m.value)
    end)
    -- Chain Lightning ('+'): the same accumulator (sums with Arcing).
    it("'+1 Maximum Additional Chains' -> MaxAdditionalChains BASE 1", function()
        local m = single(modLib.parseMod("+1 Maximum Additional Chains"))
        assert.are.equals("MaxAdditionalChains", m.name)
        assert.are.equals(1, m.value)
    end)
    it("point-scaled '+2 Maximum Additional Chains' (Chain Lightning 2pt) -> BASE 2", function()
        local m = single(modLib.parseMod("+2 Maximum Additional Chains"))
        assert.are.equals("MaxAdditionalChains", m.name)
        assert.are.equals(2, m.value)
    end)
end)

describe("Lightning Blast doublecast / quadcast parsing", function()
    it("'8% Doublecast Chance' -> DoublecastChance BASE 8", function()
        local mods, extra = modLib.parseMod("8% Doublecast Chance")
        assert.is_truthy(extra == nil or extra == "")
        local m = single(mods)
        assert.are.equals("DoublecastChance", m.name)
        assert.are.equals("BASE", m.type)
        assert.are.equals(8, m.value)
    end)
    it("point-scaled '32% Doublecast Chance' (Overcharge 4pt) -> BASE 32", function()
        local m = single(modLib.parseMod("32% Doublecast Chance"))
        assert.are.equals("DoublecastChance", m.name)
        assert.are.equals(32, m.value)
    end)
    it("'30% Quadruple Cast Chance' (Hypercharge) -> QuadrupleCastChance BASE 30", function()
        local mods, extra = modLib.parseMod("30% Quadruple Cast Chance")
        assert.is_truthy(extra == nil or extra == "")
        local m = single(mods)
        assert.are.equals("QuadrupleCastChance", m.name)
        assert.are.equals("BASE", m.type)
        assert.are.equals(30, m.value)
    end)
end)

describe("Lightning Blast chain ModCache rows are no longer silent-failure NO-OPs", function()
    it("the six chain/cast rows carry mods, not empty residue stubs", function()
        local body = assert(readFile("Data/ModCache.lua"))
        assert.is_nil(body:find('c[" Half Maximum Chains"]={{},""}', 1, true))
        assert.is_nil(body:find('c[" Lightning Blast Chains Only To First Target Hit"]={{},""}', 1, true))
        assert.is_nil(body:find('c["1 Maximum Additional Chains"]={{}," Maximum Additional Chains "}', 1, true))
        assert.is_nil(body:find('c["8% Doublecast Chance"]={{}," Doublecast Chance "}', 1, true))
        assert.is_nil(body:find('c["30% Quadruple Cast Chance"]={{}," Quadruple Cast Chance "}', 1, true))
        -- and the parsed names are present
        assert.is_truthy(body:find("LightningBlastChainsBackOnItself", 1, true))
        assert.is_truthy(body:find("MaxAdditionalChains", 1, true))
    end)
    it("CalcOffence consumes the flag on the HitSpeed lever (node-gated)", function()
        local text = assert(readFile("Modules/CalcOffence.lua"))
        assert.is_truthy(text:find("LightningBlastChainsBackOnItself", 1, true),
            "the Convergence-gated hit multiplier must stay wired")
        assert.is_truthy(text:find("LightningBlastHitMult", 1, true))
    end)
end)
