-- @leb-regression-guard:ui-accuracy-honesty-badge
-- Locks the PoB-style "accuracy honesty" UI badge: a DISPLAY-ONLY tag on a
-- build's active skill when LEB's DPS for that skill is NOT in-game +/-5%
-- verified. The badge is data-driven off data.skillAccuracyStatus
-- (src/Data/SkillAccuracyStatus.lua), generated by
-- scripts/gen_skill_accuracy_status.py from the release-board meta-43 map
-- (board_data.json -> meta_coverage.{stier,atier}).
--
-- Two-axis taxonomy (FIXED -- do not silently change the status->axis mapping):
--   board 📡 RE/feature-gated (code g) OR 🟡 gap-open (code w)  -> "approximate" (amber "~")
--   board 🔬 rig-unmeasurable (code x) OR ➖ offline (code n)   -> "unverified"  (gray  "?")
--   board ✅ +/-5% verified (code v)                            -> no entry / no badge
-- Collision rule: verified-wins. A skill in BOTH a verified and a flagged build
--   (only "Hammer Throw": Crit Hammerdin=v vs Bleed Hammerdin=g) is treated as
--   verified -> ABSENT from the table -> no badge.
--
-- DPS-NEUTRAL: the table is static reference data (like colorCodes). It is read
-- only by GUI draw code (SkillsTab:GetSkillAccuracyBadge, the slot chip, the
-- slot hover tooltip, the skill-tree info bar). It never enters modList or
-- calcsTab.mainOutput, so corpus snapshots are byte-identical. This spec must
-- never construct calc output; it only asserts the data + the display mapping.
--
-- See REGRESSION_GUARDS.md "ui-accuracy-honesty-badge".

describe("SkillAccuracyHonestyBadge #skills", function()
	local statusMap = LoadModule("Data/SkillAccuracyStatus")

	-- Representative builds for each board status code, mapped to their exact
	-- grantedEffect.name (as resolved by the generator's BUILD_TO_SKILL table).
	local APPROXIMATE = {
		["Shadow Rend"]      = "Shadow Rend BD (📡 g / count-state)",
		["Flay"]             = "Flay Mana Lich (📡 g)",
		["Harvest"]          = "Harvest Flay Lich (📡 g)",
		["Shatter Totem"]    = "Shatter Totem Druid (📡 g)",
		["Summon Sabertooth"]= "Sabertooth BM (📡 g)",
		["Hydrahedron"]      = "Hydrahedron RM (📡 g)",
		["Profane Veil"]     = "Profane Veil Warlock (🟡 w)",
		["Profane Orb"]      = "Profane Veil Warlock (🟡 w / Profane Orb x2 UNDER)",
	}
	local UNVERIFIED = {
		["Heartseeker"]      = "Heartseeker Mksm (🔬 x / crit-attribution wall)",
		["Summon Raptor"]    = "Raptor BM (🔬 x / measurement unavailable)",
	}
	-- ✅-verified skills (code v) that must carry NO badge, plus the verified-wins
	-- collision skill (Hammer Throw) and a plain untracked skill.
	local NO_BADGE = {
		"Shatter Strike", "Shadow Cascade", "Bladestorm", "Smite", "Rive",
		"Chaos Bolts", "Abyssal Echoes", "Hail of Arrows", "Glacier",
		"Javelin",        -- board 2026-07-16: Javelin Paladin 🔬 x -> ✅ v (verified) -> no badge
		"Hammer Throw",   -- verified-wins (Crit Hammerdin v vs Bleed Hammerdin g)
		"Fireball",       -- untracked ordinary skill
	}

	it("table shape: every value is exactly 'approximate' or 'unverified'", function()
		assert.is_table(statusMap, "SkillAccuracyStatus must return a table")
		for name, axis in pairs(statusMap) do
			assert.is_string(name)
			assert.is_true(axis == "approximate" or axis == "unverified",
				("%s has invalid axis %q (must be approximate|unverified)"):format(name, tostring(axis)))
		end
	end)

	it("status->axis mapping: 📡/🟡 board codes map to 'approximate'", function()
		for skill, why in pairs(APPROXIMATE) do
			assert.are.equal("approximate", statusMap[skill],
				skill .. " must be 'approximate' (" .. why .. ")")
		end
	end)

	it("status->axis mapping: 🔬/➖ board codes map to 'unverified'", function()
		for skill, why in pairs(UNVERIFIED) do
			assert.are.equal("unverified", statusMap[skill],
				skill .. " must be 'unverified' (" .. why .. ")")
		end
	end)

	it("verified (✅) and verified-wins skills carry NO badge", function()
		for _, skill in ipairs(NO_BADGE) do
			assert.is_nil(statusMap[skill],
				skill .. " must have no accuracy badge (verified / verified-wins / untracked)")
		end
		-- Hammer Throw specifically: the verified-wins collision must never leak.
		assert.is_nil(statusMap["Hammer Throw"],
			"Hammer Throw is verified via Crit Hammerdin -> verified-wins -> no badge")
	end)

	it("no fabricated keys: every badged skill name exists in data.skills", function()
		local byName = {}
		for _, sk in pairs(data.skills) do
			if sk.name then byName[sk.name] = true end
		end
		for name in pairs(statusMap) do
			assert.is_true(byName[name] == true,
				name .. " must be a real grantedEffect.name in data.skills (no fabricated keys)")
		end
	end)

	it("wiring + descriptor: SkillsTab:GetSkillAccuracyBadge returns the right chip", function()
		newBuild()
		-- data table is loaded and reachable the same way the draw code reads it.
		-- (LoadModule returns a fresh table each call, so compare by content, not
		-- identity, against the copy this spec loaded at the top.)
		assert.is_table(build.data.skillAccuracyStatus,
			"data.skillAccuracyStatus must be loaded for the draw code to read")
		for name, axis in pairs(statusMap) do
			assert.are.equal(axis, build.data.skillAccuracyStatus[name],
				"data.skillAccuracyStatus must match SkillAccuracyStatus for " .. name)
		end
		local st = build.skillsTab

		-- approximate -> amber "~" chip
		local approx = st:GetSkillAccuracyBadge("Shadow Rend")
		assert.is_table(approx)
		assert.are.equal("approximate", approx.axis)
		assert.are.equal("~", approx.glyph)
		assert.are.equal("^xFF9922", approx.color)
		assert.is_true(#approx.tip > 0, "approximate badge must have tooltip lines")

		-- unverified -> gray "?" chip
		local unver = st:GetSkillAccuracyBadge("Heartseeker")
		assert.is_table(unver)
		assert.are.equal("unverified", unver.axis)
		assert.are.equal("?", unver.glyph)
		assert.are.equal("^x999999", unver.color)

		-- verified / untracked -> nil (no chip)
		assert.is_nil(st:GetSkillAccuracyBadge("Shatter Strike"))
		assert.is_nil(st:GetSkillAccuracyBadge("Hammer Throw"))
		assert.is_nil(st:GetSkillAccuracyBadge(nil))
	end)
end)
